### ISSUE TITLE
prior and new SDK versions hit compilation issue with SvrfGLTFSceneKit 

### ISSUE THREAD

**Issue by piemonte** [Svrf/svrf-ios-sdk#63]
# Bug report

Hey friends, when trying to install any version of SvrfSDK, I encountered a compilation issue with an internal framework, 'SvrfGLTFSceneKit'.

## Describe the bug

Build SvrfSDK.

```
SvrfGLTFSceneKit Group
Swift Compiler Error Group
/Bridge/Pods/SvrfGLTFSceneKit/Source/Common/GLTFTypes.swift:168:51: 'zero' has been renamed to 'kCMTimeZero'
```

### Steps to reproduce

1. Using Xcode Version 10.2.1, build a Swift 5 target using the SvrfSDK.

**Comment by brentchow** [comment]
Still having issues. Actively investigating.

**Comment by brentchow** [comment]
[SvrfGLTFSceneKit v1.2.1](https://github.com/Svrf/SvrfGLTFSceneKit/releases/tag/1.2.1) should resolve this issue, but for some reason the SvrfSDK project's build settings for the library are stuck on Swift 4 instead of Swift 5. A workaround is to manually change SvrfSDK's SvrfGLTFSceneKit build settings to Swift 5.

@AndreiEvstratenko is continuing to look at this and we're hoping to have a full fix by tomorrow.

**Comment by piemonte** [comment]
hey ya'll, thanks for the fast response. i'm not blocked by it but wanted to let you know. 👍
